appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fkHtAO/RQKtCEX8gAahR29jyKRLQUzjKTno7G8VCaWnDTuj1j3tLRO/44vTnOlQDtLjX+Z9iINAyoxaRkO9Uv01dmxqPjPusNugxAyN9cLDNYqltPM4r7FzDt08Aw9cP2MGHFrotzeu0QP82D1pg5XT1Z9HVftZ4z/c+EzkDPAGABANNiwFNDAhvwaBVLB4pvHMb23n7ZlC5vFCSo+sn5q3JQdV9s3R7Rm222vLwhJy2X4yHqDyngkWMXdMOwD8knbld/l7qEAdfs4oL/bIfZU3bsniTNf2gC3SM86BnqUakB5Kt5NTR8p1nEwnkNWiPTs1jybgyuvtVoiFl0xqFcPXa5CuoTenc+PaOmCNZyXJAyEYuQr7aUEC7odtvediPOW/7CyVt3vPqNLugEan1uF7LurZN1WdYsS+rwMOG6ZKYSRyzWvwt1i1SHukxRC8tpeIm9VTjG3H5IYCd4ct7okWwDVUPlg3AOt5vzCXRr23uyuGm2nMOdlMumQiWNZkBaNaLYEeLVmSgGeR+gxY74rH+1KkYAGTFRq0kDOzIK9q3TlcnLDQGO8ZBIUQEVO1x42lH87FGHLL86/0P4P3P7nmHmScu/8LHYLVwX2quftVzJJYItlk6pJIA8CdzTCO6aH7fSCG4P2lAZRyKyh2m7wsRKbmIXsxIcderyDP6UUs=}
provider:
  win: azure
bot:
  automerge: true
